In [ ]:
# Otliers
#Q3 + IQR*1.5  = upper Quartile Range
#Q1 - IQR*1.5  = lower Quartile Range
#Z-Score Meethod for Outlier Method
## Z = 1-> Slight Deviaion, Z = 2 -> Moderate Deviation, Z = 3 -> Extreme Deviation, then starts Outliers
# Handle Outliers

In [ ]:
import seaborn as sns
import pandas as pd
df = dataset
# Load the Titanic dataset
titanic = sns.load_dataset('titanic')

# Display the first few rows of the dataset
print(titanic.head())

# Calculate the IQR for the 'age' column
Q1 = titanic['age'].quantile(0.25)
Q3 = titanic['age'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds for the outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Remove outliers
titanic_no_outliers = titanic[(titanic['age'] >= lower_bound) & (titanic['age'] <= upper_bound)]

# Display the first few rows of the dataset without outliers
print(titanic_no_outliers.head())

In [ ]:
# Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
titanic = sns.load_dataset('titanic')

# View the first few rows of the dataset
titanic.head()

# Check for null values
titanic.isnull().sum()

# Handle missing data (if necessary)
# For example, you can fill in missing age values with the mean age of the respective class
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].mean())

# Drop unnecessary columns (if necessary)
# For example, you can drop the 'Name' column if it's not needed
titanic = titanic.drop(columns=['Name'])

# Create a histogram for the age distribution
sns.hist(titanic['Age'])
plt.show()

# Create a box plot for the fare distribution
sns.boxplot(titanic['Fare'])
plt.show()

# Create a heatmap for the correlation between features
sns.heatmap(titanic.corr(), annot=True, cmap='coolwarm')
plt.show()

# Example: Create an age range column
titanic['Age_range'] = titanic['Age'].apply(lambda x: 'Young' if x < 30 else 'Old')

# Example: Calculate the central tendencies and IQR for the fare column
titanic['Fare'].describe()

# Summarize the findings
print("The dataset contains", titanic.shape[0], "rows and", titanic.shape[1], "columns.")
print("The average fare is", titanic['Fare'].mean())
print("The median fare is", titanic['Fare'].median())

# Drop unnecessary columns (if necessary)
# For example, you can drop the 'Age_range' column if it's not needed
titanic = titanic.drop(columns=['Age_range'])

In [ ]:
# Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
titanic = sns.load_dataset('titanic')

# View the first few rows of the dataset
titanic.head()

# Check for null values
titanic.isnull().sum()

# Handle missing data (if necessary)
# For example, you can fill in missing age values with the mean age of the respective class
titanic['age'] = titanic['age'].fillna(titanic['age'].mean())

# Drop unnecessary columns (if necessary)
# For example, you can drop the 'Name' column if it's not needed
# Drop the 'points' column from the DataFrame
titanic = titanic.drop(columns=['points'], axis=1)

# Create a histogram for the age distribution
plt.hist(titanic['age'])
plt.show()

# Create a box plot for the fare distribution
sns.boxplot(titanic['fare'])
plt.show()

# Create a heatmap for the correlation between features
sns.heatmap(titanic.corr(), annot=True, cmap='coolwarm')
plt.show()

# Example: Create an age range column
titanic['age_range'] = titanic['age'].apply(lambda x: 'Young' if x < 30 else 'Old')

# Example: Calculate the central tendencies and IQR for the fare column
titanic['fare'].describe()

# Summarize the findings
print("The dataset contains", titanic.shape[0], "rows and", titanic.shape[1], "columns.")
print("The average fare is", titanic['fare'].mean())
print("The median fare is", titanic['fare'].median())

# Drop unnecessary columns (if necessary)
# For example, you can drop the 'age_range' column if it's not needed
titanic = titanic.drop(columns=['age_range'])

In [10]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200